#!/bin/bash

# CotizaBot - Instrucciones de Configuración del Webhook
# Este script muestra toda la información necesaria

clear

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║             🤖 CotizaBot - Configuración de Webhook              ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

# Verificar estado del backend
echo "📊 Verificando estado del sistema..."
echo ""

if curl -s http://localhost:8001/api/health > /dev/null 2>&1; then
    echo "✅ Backend: FUNCIONANDO"
else
    echo "❌ Backend: NO RESPONDE"
    echo "   Intentando reiniciar..."
    sudo supervisorctl restart backend
    sleep 3
fi

# Verificar productos
PRODUCTOS=$(curl -s http://localhost:8001/api/productos 2>/dev/null | python3 -c "import sys,json; data=json.load(sys.stdin); print(len(data))" 2>/dev/null || echo "0")
echo "✅ Catálogo: $PRODUCTOS productos cargados"

# Verificar credenciales
if grep -q "ACac9ca1438699c556cf97342cbf422ca5" /app/backend/.env; then
    echo "✅ Twilio: Credenciales configuradas"
else
    echo "⚠️  Twilio: Credenciales no encontradas"
fi

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                  PASO 1: CONFIGURAR NGROK                         ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Para exponer tu backend localmente, necesitas ngrok:"
echo ""
echo "1️⃣  Crea una cuenta gratuita:"
echo "   👉 https://dashboard.ngrok.com/signup"
echo ""
echo "2️⃣  Obtén tu authtoken:"
echo "   👉 https://dashboard.ngrok.com/get-started/your-authtoken"
echo ""
echo "3️⃣  Configura ngrok con tu token:"
echo "   📋 Ejecuta: ngrok config add-authtoken TU_TOKEN_AQUI"
echo ""
echo "4️⃣  Inicia el túnel:"
echo "   📋 Ejecuta: ngrok http 8001"
echo ""
echo "5️⃣  Copia la URL pública que aparece:"
echo "   Ejemplo: https://abc123.ngrok.io"
echo ""

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║              PASO 2: CONFIGURAR WEBHOOK EN TWILIO                 ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Una vez que tengas la URL de ngrok:"
echo ""
echo "1️⃣  Ve a Twilio Console:"
echo "   👉 https://console.twilio.com/us1/develop/sms/try-it-out/whatsapp-learn"
echo ""
echo "2️⃣  En la sección 'Sandbox Configuration':"
echo "   - Campo: WHEN A MESSAGE COMES IN"
echo "   - URL: https://TU-URL-NGROK.io/api/webhook/twilio/whatsapp"
echo "   - Método: POST"
echo "   - Click en 'Save'"
echo ""
echo "   📋 Ejemplo completo:"
echo "   https://abc123.ngrok.io/api/webhook/twilio/whatsapp"
echo ""

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║           PASO 3: UNIRTE AL SANDBOX DE WHATSAPP                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "1️⃣  En la misma página de Twilio Console, verás:"
echo "   'To connect, send \"join [palabra]\" to +1 415 523 8886'"
echo ""
echo "2️⃣  Desde tu WhatsApp personal:"
echo "   - Abre WhatsApp"
echo "   - Envía mensaje a: +1 415 523 8886"
echo "   - Texto: join palabra-que-te-dieron"
echo "   - Ejemplo: 'join stone-lamp' o 'join happy-tiger'"
echo ""
echo "3️⃣  Recibirás confirmación de Twilio cuando estés conectado"
echo ""

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                    PASO 4: PROBAR EL SISTEMA                      ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Envía este mensaje de prueba al número de Twilio:"
echo ""
echo "📱 Mensaje:"
echo "   'Hola, necesito cotizar 10 tablarocas antimoho'"
echo ""
echo "✅ Respuesta esperada (en 3-5 segundos):"
echo "   Cotización para Cliente:"
echo "   • Tablaroca antimoho USG: 10 Pieza x \$340.10 = \$3,401.00 MXN"
echo "   Subtotal: \$3,401.00 MXN"
echo "   IVA (16%): \$544.16 MXN"
echo "   Total: \$3,945.16 MXN"
echo ""

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                 COMANDOS ÚTILES DE MONITOREO                      ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Ver logs del backend en tiempo real:"
echo "  📋 tail -f /var/log/supervisor/backend.out.log"
echo ""
echo "Ver errores del backend:"
echo "  📋 tail -f /var/log/supervisor/backend.err.log"
echo ""
echo "Verificar salud del sistema:"
echo "  📋 curl http://localhost:8001/api/health"
echo ""
echo "Ver dashboard web:"
echo "  🌐 http://localhost:3000"
echo ""
echo "Ver panel de ngrok (una vez iniciado):"
echo "  🌐 http://localhost:4040"
echo ""

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                    EJEMPLOS DE MENSAJES                           ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Cotización simple:"
echo "  💬 'Cuánto cuesta la tablaroca antimoho?'"
echo ""
echo "Cotización múltiple:"
echo "  💬 'Necesito 15 tablarocas ultralight y 10 canales'"
echo ""
echo "Consulta de stock:"
echo "  💬 'Tienen disponible Durock USG?'"
echo ""
echo "Pregunta general:"
echo "  💬 'Para qué sirve el Redimix?'"
echo ""

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                      TROUBLESHOOTING                              ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Si no recibes respuesta del bot:"
echo ""
echo "1. Verifica que ngrok esté corriendo:"
echo "   📋 curl http://localhost:4040/api/tunnels"
echo ""
echo "2. Verifica que el webhook esté configurado en Twilio"
echo ""
echo "3. Verifica que te uniste al sandbox:"
echo "   Envía 'join codigo' nuevamente"
echo ""
echo "4. Revisa los logs del backend:"
echo "   📋 tail -n 50 /var/log/supervisor/backend.err.log"
echo ""

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                    RESUMEN DE COMANDOS                            ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "# Configurar ngrok (una sola vez):"
echo "ngrok config add-authtoken TU_TOKEN"
echo ""
echo "# Iniciar túnel ngrok:"
echo "ngrok http 8001"
echo ""
echo "# Ver logs en tiempo real:"
echo "tail -f /var/log/supervisor/backend.out.log"
echo ""
echo "# Reiniciar backend:"
echo "sudo supervisorctl restart backend"
echo ""
echo "# Ver productos del catálogo:"
echo "curl http://localhost:8001/api/productos | jq '.[].nombre'"
echo ""

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                    INFORMACIÓN ADICIONAL                          ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "📚 Documentación completa:"
echo "   - /app/README.md"
echo "   - /app/ARQUITECTURA.md"
echo "   - /app/TWILIO_SETUP.md"
echo "   - /app/GUIA_WEBHOOK_TWILIO.md"
echo ""
echo "🔑 Credenciales configuradas:"
echo "   - Twilio Account SID: ACac9ca143..."
echo "   - Twilio Auth Token: Configurado ✓"
echo "   - Emergent LLM Key: Configurado ✓"
echo ""
echo "📊 Dashboard local:"
echo "   http://localhost:3000"
echo ""
echo "⚠️  NOTA IMPORTANTE:"
echo "   Ngrok gratuito se desconecta cada 2 horas."
echo "   Necesitarás reiniciar el túnel cuando eso ocurra."
echo ""

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                  ✅ SISTEMA LISTO PARA USAR                       ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "El sistema CotizaBot está completamente configurado."
echo "Solo necesitas seguir los pasos de arriba para conectar WhatsApp."
echo ""
echo "¿Necesitas ayuda? Revisa la documentación en /app/"
echo ""
